# Generated by Django 5.0.3 on 2024-03-18 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('price', models.FloatField(verbose_name='цена')),
                ('content', models.TextField(verbose_name='описание')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата добавление')),
                ('is_published', models.BooleanField(default=True, verbose_name='публичность')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='product.category', verbose_name='категория')),
                ('tags', models.ManyToManyField(blank=True, related_name='news', to='product.tag', verbose_name='теги')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='media/', verbose_name='фотографии')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image', to='product.product')),
            ],
            options={
                'verbose_name': 'фотография',
                'verbose_name_plural': 'фотографии',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('value', models.CharField(max_length=100, verbose_name='значение')),
                ('link', models.URLField(blank=True, null=True, verbose_name='ссылка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='product.product')),
            ],
            options={
                'verbose_name': 'атрибут продукта',
                'verbose_name_plural': 'атрибуты продуктов',
            },
        ),
    ]
